name: "publish"
on:
  push:
    tags:
      - "**[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - platform: macos-latest
            args: "--target universal-apple-darwin"

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v5
    - name: setup node
      uses: actions/setup-node@v5
      with:
        node-version: 20
    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-apple-darwin
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: install app dependencies and build it
      run: yarn && yarn build
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
      with:
        tagName: __VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "App v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false
        includeUpdaterJson: true
        updaterJsonKeepUniversal: true
        args: ${{ matrix.args }}
